-- Categories table
CREATE TABLE IF NOT EXISTS categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Districts table
CREATE TABLE IF NOT EXISTS districts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(name, category_id)
);

-- Articles table
CREATE TABLE IF NOT EXISTS articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  video_url TEXT,
  author TEXT DEFAULT 'Admin',
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  district_id BIGINT REFERENCES districts(id) ON DELETE SET NULL,
  is_hero_slider BOOLEAN DEFAULT false,
  is_top_hero BOOLEAN DEFAULT false,
  whatsapp_link TEXT,
  image_storage_path TEXT,
  is_expiring BOOLEAN DEFAULT true NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc'::text, now()) + INTERVAL '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Editable breaking-news items shown in the header ticker
CREATE TABLE IF NOT EXISTS breaking_news (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  link_url TEXT,
  image_storage_path TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  is_expiring BOOLEAN DEFAULT true NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc'::text, now()) + INTERVAL '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Homepage right-column banner advertisements
CREATE TABLE IF NOT EXISTS sidebar_ads (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  image_url TEXT NOT NULL,
  image_storage_path TEXT,
  link_url TEXT,
  alt_text TEXT,
  is_active BOOLEAN DEFAULT true NOT NULL,
  display_order INTEGER DEFAULT 0 NOT NULL,
  is_expiring BOOLEAN DEFAULT true NOT NULL,
  expires_at TIMESTAMP WITH TIME ZONE DEFAULT (timezone('utc'::text, now()) + INTERVAL '7 days'),
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initial Categories
INSERT INTO categories (name, slug)
SELECT v.name, v.slug
FROM (
  VALUES
    ('Latest News', 'latest-news'),
    ('Telangana', 'telangana'),
    ('Andhra Pradesh', 'andhra-pradesh'),
    ('National', 'national'),
    ('International', 'international'),
    ('Politics', 'politics'),
    ('Crime', 'crime'),
    ('Movie', 'movie'),
    ('Lifestyle', 'lifestyle'),
    ('Business', 'business'),
    ('Technology', 'technology'),
    ('Sports', 'sports'),
    ('Videos', 'videos'),
    ('Education', 'education'),
    ('Health', 'health'),
    ('Spiritual', 'spiritual'),
    ('Photos', 'photos'),
    ('E-Paper', 'e-paper'),
    ('Complaints', 'complaints'),
    ('Jobs', 'jobs'),
    ('Opinion', 'opinion')
) AS v(name, slug)
WHERE NOT EXISTS (
  SELECT 1 FROM categories c WHERE c.name = v.name OR c.slug = v.slug
);

-- Initial Districts (Telangana)
DO $$
DECLARE
  telangana_id BIGINT;
BEGIN
  SELECT id INTO telangana_id FROM categories WHERE name = 'Telangana';

  INSERT INTO districts (name, category_id)
  SELECT v.name, telangana_id
  FROM (
    VALUES
      ('Hyderabad'),
      ('Karimnagar'),
      ('Nalgonda'),
      ('Adilabad'),
      ('Nizamabad'),
      ('Mahabubnagar'),
      ('Warangal'),
      ('Khammam'),
      ('Medak')
  ) AS v(name)
  WHERE NOT EXISTS (
    SELECT 1 FROM districts d WHERE d.name = v.name AND d.category_id = telangana_id
  );
END $$;

-- Initial Districts (Andhra Pradesh)
DO $$
DECLARE
  ap_id BIGINT;
BEGIN
  SELECT id INTO ap_id FROM categories WHERE name = 'Andhra Pradesh';

  INSERT INTO districts (name, category_id)
  SELECT v.name, ap_id
  FROM (
    VALUES
      ('Kadapa'),
      ('Guntur'),
      ('Nellore'),
      ('Vizianagaram'),
      ('Anantapur'),
      ('West Godavari'),
      ('East Godavari'),
      ('Kurnool'),
      ('Srikakulam'),
      ('Ongole'),
      ('Vizag'),
      ('Tirupati'),
      ('Vijayawada')
  ) AS v(name)
  WHERE NOT EXISTS (
    SELECT 1 FROM districts d WHERE d.name = v.name AND d.category_id = ap_id
  );
END $$;
