-- Categories table
CREATE TABLE categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Districts table
CREATE TABLE districts (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  category_id BIGINT REFERENCES categories(id) ON DELETE CASCADE,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  UNIQUE(name, category_id)
);

-- Articles table
CREATE TABLE articles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  content TEXT NOT NULL,
  image_url TEXT,
  video_url TEXT,
  author TEXT DEFAULT 'Admin',
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  district_id BIGINT REFERENCES districts(id) ON DELETE SET NULL,
  is_hero_slider BOOLEAN DEFAULT false,
  is_top_hero BOOLEAN DEFAULT false,
  whatsapp_link TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Initial Categories
INSERT INTO categories (name, slug) VALUES 
('Latest News', 'latest-news'),
('Telangana', 'telangana'),
('Andhra Pradesh', 'andhra-pradesh'),
('National', 'national'),
('International', 'international'),
('Politics', 'politics'),
('Crime', 'crime'),
('Movie', 'movie'),
('Lifestyle', 'lifestyle'),
('Business', 'business'),
('Technology', 'technology'),
('Sports', 'sports'),
('Videos', 'videos'),
('Education', 'education'),
('Health', 'health'),
('Spiritual', 'spiritual'),
('Photos', 'photos'),
('E-Paper', 'e-paper'),
('Complaints', 'complaints'),
('Jobs', 'jobs'),
('Opinion', 'opinion');

-- Initial Districts (Telangana)
DO $$
DECLARE
  telangana_id BIGINT;
BEGIN
  SELECT id INTO telangana_id FROM categories WHERE name = 'Telangana';
  INSERT INTO districts (name, category_id) VALUES 
  ('Hyderabad', telangana_id),
  ('Karimnagar', telangana_id),
  ('Nalgonda', telangana_id),
  ('Adilabad', telangana_id),
  ('Nizamabad', telangana_id),
  ('Mahabubnagar', telangana_id),
  ('Warangal', telangana_id),
  ('Khammam', telangana_id),
  ('Medak', telangana_id);
END $$;

-- Initial Districts (Andhra Pradesh)
DO $$
DECLARE
  ap_id BIGINT;
BEGIN
  SELECT id INTO ap_id FROM categories WHERE name = 'Andhra Pradesh';
  INSERT INTO districts (name, category_id) VALUES 
  ('Kadapa', ap_id),
  ('Guntur', ap_id),
  ('Nellore', ap_id),
  ('Vizianagaram', ap_id),
  ('Anantapur', ap_id),
  ('West Godavari', ap_id),
  ('East Godavari', ap_id),
  ('Kurnool', ap_id),
  ('Srikakulam', ap_id),
  ('Ongole', ap_id),
  ('Vizag', ap_id),
  ('Tirupati', ap_id),
  ('Vijayawada', ap_id);
END $$;
